# Lab 4 - NumPy and Pandas Exercises

**Topic:** NumPy and Pandas fundamentals and intermediate operations

**Total Exercises:** 13

**Estimated Time:** 60-90 minutes

# Table of Contents

1. [Test for Non-Zero Elements](#test-for-non-zero-elements-level-1)
2. [Element-wise Comparisons Between Two Arrays](#element-wise-comparisons-between-two-arraarray2s-level-1)
3. [Create Array of Zeros, Ones, and Fives](#create-array-of-zeros-ones-and-fives-level-1)
4. [Add Vector to Matrix Rows](#add-vector-to-matrix-rows-level-2)
5. [5x5 Array with Border Pattern](#5x5-array-with-border-pattern-level-2)
6. [Find Common Values Between Arrays](#find-common-values-between-arrays-level-1)
7. [Stack and Split Arrays](#stack-and-split-arrays-level-2)
8. [Get First Three Rows of DataFrame](#get-first-three-rows-of-dataframe-level-1)
9. [Select Rows by Attempts](#select-rows-by-attempts-level-1)
10. [Count Rows and Columns](#count-rows-and-columns-level-1)
11. [Select Rows by Score Range](#select-rows-by-score-range-level-1)
12. [Change Score in Row 'c'](#change-score-in-row-c-level-1)
13. [Calculate Mean Score per Student](#calculate-mean-score-per-student-level-2)

## Learning Objectives

| Objective | Skills Developed |
|---|---|
| Work with NumPy arrays | Array creation, element-wise comparison, broadcasting |
| Manipulate and combine arrays | Stacking, splitting, axis operations |
| Use Pandas for DataFrame tasks | Selection, filtering, modification, aggregation |

## NumPy Basic Exercises

### Test for Non-Zero Elements (Level 1)
Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
# Test for Non-Zero Elements (Level 1)
import numpy as np

non_zero_array = np.arange(1, 3)
zero_array = np.zeros(2)
np.all(non_zero_array), np.all(zero_array)

(np.True_, np.False_)

### Element-wise Comparisons Between Two Arrays (Level 1)
Given array1 = [45, 67, 23] and array2 = [56, 23, 89], create element-wise comparisons: greater, greater_equal, less, less_equal.

In [3]:
# Element-wise Comparisons Between Two Arrays (Level 1)
array1 = np.array([45, 67, 23])
array2 = np.array([56, 23, 89])

print("1. Comparison of greater is: ", np.greater(array1, array2))
print("2. Comparison of greater_equal is: ", np.greater_equal(array1, array2))
print("3. Comparison of less is: ", np.less(array1, array2))
print("4. Comparison of less_equal is:", np.less_equal(array1, array2))

1. Comparison of greater is:  [False  True False]
2. Comparison of greater_equal is:  [False  True False]
3. Comparison of less is:  [ True False  True]
4. Comparison of less_equal is: [ True False  True]


### Create Array of Zeros, Ones, and Fives (Level 1)
Create an array containing 8 zeros, 5 ones, and 10 fives (concatenated as a single 1D array).

In [7]:
# Create Array of Zeros, Ones, and Fives (Level 1)
eight_zeros = np.zeros(8)
five_ones = np.ones(5)
ten_fives = np.ones(10) * 5
zeros_ones_fives_array = np.hstack([eight_zeros, five_ones, ten_fives])
zeros_ones_fives_array

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5.])

## NumPy Array Operations

### Add Vector to Matrix Rows (Level 2)
Add vector v = [2, 0, 2] to each row of matrix m with rows: [23,45,11], [12,23,54], [29,19,34], [1,23,10].

In [10]:
# Add Vector to Matrix Rows (Level 2)
v = np.array([2, 0, 2])
m = np.array(([23,45,11], [12,23,54], [29,19,34], [1,23,10]))
m_w_v = np.vstack([m, v])
m_w_v

array([[23, 45, 11],
       [12, 23, 54],
       [29, 19, 34],
       [ 1, 23, 10],
       [ 2,  0,  2]])

### 5x5 Array with Border Pattern (Level 2)
Create a 5x5 2D array with value 1 on the border and value 25 in the interior.

In [12]:
# 5x5 Array with Border Pattern (Level 2)
five_five_array = np.ones((5, 5))
five_five_array[1: 4, 1: 4] = 25
five_five_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1., 25., 25., 25.,  1.],
       [ 1., 25., 25., 25.,  1.],
       [ 1., 25., 25., 25.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### Find Common Values Between Arrays (Level 1)
Find common values between Array1 = [23, 45, 11, 5] and Array2 = [23, 5, 1].

In [15]:
# Find Common Values Between Arrays (Level 1)
array1 = np.array([23, 45, 11, 5])
array2 = np.array([23, 5, 1])
np.intersect1d(array1, array2)

array([ 5, 23])

### Stack and Split Arrays (Level 2)
Perform horizontal stacking and vertical stacking; also split the combined arrays horizontally and vertically.
Array1 rows: [23,45,11], [12,23,54], [1,23,10]
Array2 rows: [3,5,1], [2,3,4], [9,1,5]

In [14]:
# Stack and Split Arrays (Level 2)
array1 = np.array(([23,45,11], [12,23,54], [1,23,10]))
array2 = np.array(([3,5,1], [2,3,4], [9,1,5]))
hori_stacking_array = np.hstack([array1, array2])
vert_stacking_array = np.vstack([array1, array2])
splitted_hori_stacking_array = np.hsplit(hori_stacking_array, 2)
splitted_vert_stacking_array = np.vsplit(vert_stacking_array, 2)
hori_stacking_array, vert_stacking_array, splitted_hori_stacking_array, splitted_vert_stacking_array

(array([[23, 45, 11,  3,  5,  1],
        [12, 23, 54,  2,  3,  4],
        [ 1, 23, 10,  9,  1,  5]]),
 array([[23, 45, 11],
        [12, 23, 54],
        [ 1, 23, 10],
        [ 3,  5,  1],
        [ 2,  3,  4],
        [ 9,  1,  5]]),
 [array([[23, 45, 11],
         [12, 23, 54],
         [ 1, 23, 10]]),
  array([[3, 5, 1],
         [2, 3, 4],
         [9, 1, 5]])],
 [array([[23, 45, 11],
         [12, 23, 54],
         [ 1, 23, 10]]),
  array([[3, 5, 1],
         [2, 3, 4],
         [9, 1, 5]])])

## Pandas DataFrame Exercises

Consider the following dataframe for the remaining tasks <br>
Sample DataFrame : 

In [16]:
assessment_results = {
    'name': ['Anastasia', 'Paul', 'Kathe', 'Joseph', 'Linda', 'Michael', 'Matt', 'Laurentine', 'Chirstian', 'Jonas'], 
    'score': [12.5, 10, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### Get First Three Rows of DataFrame (Level 1)
Write a Pandas program to get the first 3 rows of a given DataFrame.

In [ ]:
# Get First Three Rows of DataFrame (Level 1)
import pandas as pd

### Select Rows by Attempts (Level 1)
Select rows where the number of attempts in the exam is greater than 2.

In [ ]:
# Select Rows by Attempts (Level 1)
# TODO: Write your code here

### Count Rows and Columns (Level 1)
Count the number of rows and columns in a DataFrame.

In [ ]:
# Count Rows and Columns (Level 1)
# TODO: Write your code here

### Select Rows by Score Range (Level 1)
Select rows where the score is between 14 and 20 (inclusive).

In [ ]:
# Select Rows by Score Range (Level 1)
# TODO: Write your code here

### Change Score in Row 'c' (Level 1)
Change the score in row label 'c' to 11.5.

In [ ]:
# Change Score in Row 'c' (Level 1)
# TODO: Write your code here

### Calculate Mean Score per Student (Level 2)
Calculate the mean score for each different student in the DataFrame (handle missing values appropriately).

In [ ]:
# Calculate Mean Score per Student (Level 2)
# TODO: Write your code here

## Reflection / Next Steps
- Execute and test each code cell
- Add brief comments explaining your approach for each exercise
- Extend exercises with additional edge cases if desired